### ISSUE TITLE
Mouse buttons don't work

### ISSUE THREAD

**Issue by mp3o7** [nxtdaydelivery/quickF5#1]
I love this mod but I'm used to switch perspective with my mouse side buttons, but when I bind them in controls it doesn't work.

**Comment by nextdayy** [comment]
hi, this mod has been rewritten by one of my colleagues, you can find it at https://github.com/Polyfrost/BehindYouV3. Hope this helps!

**Comment by mp3o7** [comment]
Oh tysm! The download link doesn't seem to work but I guess I'll download the zip or someting.

**Comment by mp3o7** [comment]
Nvm I'm stupid. Found the jar file. Thanks!

**Comment by nextdayy** [comment]
That's all good. Thanks for your support! :)
make sure to check out discord.gg/polyfrost for more cool mods and stuff :)
